Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/zesty64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end
end

